# Configuraci√≥n para air (hot reload)
root = "."

[build]
  cmd = "go build -o tmp/main.exe ./cmd/main.go"
  bin = "tmp/main.exe"
  include_ext = [".go", ".yaml"]
  exclude_dir = ["tmp"]
  delay = 1000

[log]
  color = "auto"
  time = true

[watch]
  dirs = ["."]
  exclude = ["tmp"]
